import Board from '@components/Board'
import Game from '@components/Game'
import Head from 'next/head'




export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen py-20">
        <Game dimension={5} key="Game-4" />
      </main>


    </div>
  )
}
